// Generated by github.com/davyxu/protoplus
package tests

import (
	"github.com/davyxu/cellnet/codec"
	"github.com/davyxu/cellnet/meta"
	"reflect"
)

var (
	_ cellmeta.Meta
	_ cellcodec.CodecRecycler
	_ reflect.Kind
)

func init() {

	cellmeta.Register(&cellmeta.Meta{
		Codec: cellcodec.MustGetByName("protoplus"),
		Type:  reflect.TypeOf((*MyTypeMini)(nil)).Elem(),
		ID:    0,
		New:   func() interface{} { return &MyTypeMini{} },
	})
	cellmeta.Register(&cellmeta.Meta{
		Codec: cellcodec.MustGetByName("protoplus"),
		Type:  reflect.TypeOf((*MySubType)(nil)).Elem(),
		ID:    0,
		New:   func() interface{} { return &MySubType{} },
	})
	cellmeta.Register(&cellmeta.Meta{
		Codec: cellcodec.MustGetByName("protoplus"),
		Type:  reflect.TypeOf((*MyType)(nil)).Elem(),
		ID:    0,
		New:   func() interface{} { return &MyType{} },
	})
	cellmeta.Register(&cellmeta.Meta{
		Codec: cellcodec.MustGetByName("protoplus"),
		Type:  reflect.TypeOf((*LoginREQ)(nil)).Elem(),
		ID:    17076,
		New:   func() interface{} { return &LoginREQ{} },
	})
	cellmeta.Register(&cellmeta.Meta{
		Codec: cellcodec.MustGetByName("protoplus"),
		Type:  reflect.TypeOf((*LoginACK)(nil)).Elem(),
		ID:    44443,
		New:   func() interface{} { return &LoginACK{} },
	})
}
