// Generated by github.com/davyxu/protoplus
// DO NOT EDIT!
using System;
using System.Collections.Generic;
using ProtoPlus;
#pragma warning disable 162

namespace Proto
{
	
	
	
	public partial class LoginREQ : IProtoStruct 
	{
		
		#region Serialize Code
		public void Init( )
		{   
		}

		public void Marshal(OutputStream stream)
		{ 
		}

		public int GetSize()
		{
			int size = 0; 
			return size;
		}

 		public bool Unmarshal(InputStream stream, int fieldNumber, WireFormat.WireType wt)
		{
		 	switch (fieldNumber)
            { 
			default:
				return true;
            }

            return false;
		}
		#endregion
	}

	
	public partial class LoginACK : IProtoStruct 
	{
		
		#region Serialize Code
		public void Init( )
		{   
		}

		public void Marshal(OutputStream stream)
		{ 
		}

		public int GetSize()
		{
			int size = 0; 
			return size;
		}

 		public bool Unmarshal(InputStream stream, int fieldNumber, WireFormat.WireType wt)
		{
		 	switch (fieldNumber)
            { 
			default:
				return true;
            }

            return false;
		}
		#endregion
	}

}
