// Generated by github.com/davyxu/protoplus
// DO NOT EDIT!
using System;
using System.Collections.Generic;
using ProtoPlus;
#pragma warning disable 162

namespace Proto
{

	public static class MessageVisitor
    {
		public static void Visit(Action<MetaInfo> callback)
		{	
            callback(new MetaInfo
            {
				Type = typeof(MyTypeMini),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
            callback(new MetaInfo
            {
				Type = typeof(MySubType),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
            callback(new MetaInfo
            {
				Type = typeof(MyType),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
            callback(new MetaInfo
            {
				Type = typeof(LoginREQ),	
				ID = 0, 	
				SourcePeer = "client",
				TargetPeer = "game",
            });
            callback(new MetaInfo
            {
				Type = typeof(LoginACK),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
		}
    }
}
