// Generated by github.com/davyxu/protoplus
// DO NOT EDIT!
using System;
using System.Collections.Generic;
#pragma warning disable 162

namespace Proto
{
	public class MetaInfo
	{        
		public ushort ID;           // 消息ID
		public Type Type;           // 消息类型

		// 消息方向
		// 在proto中添加[MsgDir: "client -> game" ], 左边为源, 右边为目标
		public string SourcePeer;   // 消息发起的源
		public string TargetPeer;   // 消息的目标

		public string Name;
	}

	public static class MessageVisitor
    {
		public static void Visit(Action<MetaInfo> callback)
		{	
            callback(new MetaInfo
            {
				Type = typeof(MyTypeMini),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
            callback(new MetaInfo
            {
				Type = typeof(MySubType),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
            callback(new MetaInfo
            {
				Type = typeof(MyType),	
				ID = 0, 	
				SourcePeer = "",
				TargetPeer = "",
            });
            callback(new MetaInfo
            {
				Type = typeof(LoginREQ),	
				ID = 225, 	
				SourcePeer = "client",
				TargetPeer = "game",
            });
            callback(new MetaInfo
            {
				Type = typeof(LoginACK),	
				ID = 27592, 	
				SourcePeer = "",
				TargetPeer = "",
            });
		}
    }
}
